const PLAYS = [
  {id:"lead-jammer",title:"Lead Jammer",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"First jammer through the pack earns lead status — and control of the clock",
   steps:["Both jammers line up behind the pack. The first to legally break through earns lead.",
          "Teal jammer finds a gap and passes all blockers on the initial trip — ref signals lead!",
          "A jammer loses lead eligibility if they take a penalty or exit the zone without earning it.",
          "As lead jammer, teal taps her hips to call off the jam before red can score."],
   durations:[3000,3000,2800,2800],
   why:"Lead jammer controls the clock — they can end the jam at any moment, locking in their score.",
   anim:"lead",refSignal:"lead",focus:"both",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[74,27],jB:[81,36]},

  {id:"scoring-trip",title:"Scoring a Point",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"A jammer earns one point for each red blocker circle they legally pass",
   steps:["The teal jammer re-enters the pack from the rear — a new scoring trip begins.",
          "First red blocker passed! One point earned.",
          "Second red blocker cleared — two points and still going.",
          "Third red blocker behind her — three points this trip.",
          "The fourth red blocker steps in and stops the jammer. That point is denied.",
          "Three points scored this trip. The jammer's ref signals the count."],
   durations:[2600,2400,2400,2400,2800,3000],
   why:"Points aren't scored all at once — every red blocker circle is a separate obstacle. Even one block prevents that point.",
   anim:"lap",refSignal:"scoring",focus:"b",
   jamSteps:[[82,38],[62,22],[52,19],[44,19],[40,21],[40,21]],
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"call-off",title:"Calling Off the Jam",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"Lead jammer ends the jam early by tapping both hands to their hips",
   steps:["Teal jammer has lead status and has just completed a scoring pass.",
          "Red jammer is catching up and about to score — teal needs to act fast.",
          "Teal jammer repeatedly taps both hands to their hips — the ref whistles the jam dead.",
          "Teal's points are locked in. Red never gets their scoring trip."],
   durations:[2800,2800,2800,2600],
   why:"Timing the call-off is a core skill — too early leaves points on the table, too late lets the opponent score.",
   anim:"lap",refSignal:"calloff",focus:"both",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[50,18]},

  {id:"star-pass",title:"Star Pass",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"The jammer can hand the star to the pivot, transferring the jammer role",
   steps:["Teal jammer is stuck and decides to pass the role to the pivot.",
          "The jammer hands the star to their pivot — both must be upright, in bounds, and in play.",
          "The pivot puts on the star and is now the jammer, inheriting all points scored so far.",
          "The original jammer becomes a blocker. The fresh jammer has a new angle of attack."],
   durations:[2800,3200,2800,2800],
   why:"A star pass is a surprise tactical reset — it can catch the opposing team completely off guard.",
   anim:"wall",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"scoring-avoidance",title:"Scoring Avoidance",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"Blockers can skate out of bounds to deny the jammer a point",
   steps:["Teal jammer approaches red blocker, about to pass and earn a point.",
          "Red blocker steps out of bounds — no point is earned on an out-of-bounds skater.",
          "Jammer passes the out-of-bounds blocker, but no point is awarded.",
          "The blocker returns in bounds — but must re-enter behind the jammer.",
          "The blocker is now at the back of the pack. They denied one point but lost their blocking position for the next pass."],
   durations:[2800,3000,2800,2800,3500],
   why:"Stepping out denies one point but puts the blocker out of position — a skilled jammer can bait blockers into doing this repeatedly to clear their own path.",
   anim:"lap",refSignal:"oob",focus:"b",
   stepPositions:{
     1: [["a",0,[38,4]]],
     2: [["a",0,[38,4]]],
     3: [["a",0,[38,20]]],
   },
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"apex-jump",title:"Apex Jump",cat:"Jamming",catColor:"var(--cat-scoring)",
   teaser:"A jammer leaps over the inner track boundary at a curve to shortcut past the entire pack",
   steps:["Teal jammer approaches the curve at speed, hugging the inner boundary.",
          "The jammer launches — leaping over the inner boundary and into the air.",
          "Airborne over the inner oval, passing all blockers mid-air.",
          "First skate lands back in bounds — all passed blockers count. Points scored!"],
   durations:[2800,3000,3000,2800],
   why:"A successful apex jump can pass the entire pack in one move. If the landing is out of bounds, no penalty — they just re-enter behind the pack and try again.",
   anim:"apex",refSignal:"scoring",focus:"b",
   // jammer B step positions: on approach, at peak (inner boundary), over oval, landed
   jamSteps:[[18,61],[26,32],[43,22],[65,21]],
   bA:[[37,20],[45,18],[54,18],[62,20]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"the-wall",title:"The Wall",cat:"Blocking",catColor:"var(--cat-blocking)",
   teaser:"Blockers form a shoulder-to-shoulder line to seal the entire track",
   steps:["Three red blockers form a wall spanning the full width of the track.",
          "Teal jammer approaches at speed — there's no obvious gap to exploit.",
          "Jammer tries the inside line; the wall steps together and closes it.",
          "Jammer is forced to slow and wait — the wall is controlling the pack speed."],
   durations:[2800,3000,2800,2600],
   why:"A solid wall can hold a jammer for the entire jam, completely shutting down scoring.",
   anim:"wall",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"recycling",title:"Recycling",cat:"Blocking",catColor:"var(--cat-blocking)",
   teaser:"Blockers slow down to rejoin the pack and block again after being passed",
   steps:["Teal jammer has passed red blocker — that blocker is now behind the jammer.",
          "The passed red blocker slows and drops back into the rear of the pack.",
          "Now back in position, the blocker rejoins the wall for another run at the jammer.",
          "Constant recycling keeps the defense dense — the jammer can never get a clean run."],
   durations:[2800,2800,2800,2600],
   why:"Being passed doesn't end your job. Recycling back is what makes derby defense continuous.",
   anim:"lap",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"jammer-assist",title:"Jammer Assist",cat:"Blocking",catColor:"var(--cat-blocking)",
   teaser:"Your own blocker can push or whip the jammer through the pack",
   steps:["Teal blocker positions alongside their own jammer at the back of the pack.",
          "The blocker grabs the jammer's hand or pushes from behind — a legal assist.",
          "The jammer uses the extra momentum to shoot through a gap in the red wall.",
          "Assisting your jammer is just as important as blocking theirs."],
   durations:[2800,3000,2800,2800],
   why:"Derby is a two-way game. A well-timed assist can send your jammer through the pack instantly.",
   anim:"lead",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"positional-block",title:"Positional Blocking",cat:"Blocking",catColor:"var(--cat-blocking)",
   teaser:"A blocker can impede the jammer just by being in the way — no contact needed",
   steps:["Red blocker skates in front of the teal jammer, matching speed exactly.",
          "No hit is thrown — the blocker simply occupies the space the jammer wants.",
          "Jammer tries to go around but the blocker mirrors every move.",
          "Positional blocking is perfectly legal and carries no penalty risk."],
   durations:[2800,2800,2800,2600],
   why:"You don't have to hit to block. Controlling space is often smarter.",
   anim:"wall",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"tripod",title:"The Tripod",cat:"Blocking",catColor:"var(--cat-blocking)",
   teaser:"Three blockers form a triangle — two corners hold the line while a brace skates backward to direct them",
   steps:["Two red 'corner' blockers take the inside and outside track lines, closing both edges.",
          "A third blocker — the 'brace' — skates backward in front of them, facing the jammer.",
          "The brace reads the jammer's angle and calls out which corner to shift, keeping the wall sealed.",
          "The fourth blocker is freed for offense — chasing or hitting the teal jammer if they escape."],
   durations:[2800,3000,3000,2800],
   why:"The tripod is the most common three-person defense. It's flexible enough to cover any lane while keeping one blocker available for offense.",
   anim:"tripod",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"back-block",title:"Back Block",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"Hitting an opponent in the back is always a penalty",
   steps:["Red blocker moves to hit teal but the target turns — contact lands on teal's back.",
          "The back is an illegal target zone. Forceful contact to the back is always penalized.",
          "Ref signals back block. Red must immediately skate to the penalty box.",
          "Red team skates shorthanded for 30 seconds — a real defensive disadvantage."],
   durations:[2800,2800,2800,2600],
   why:"The back is protected for safety. Even if the target turns into the hit, the initiator is responsible.",
   anim:"penalty",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"forearm-elbow",title:"Forearm / Elbow",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"Extending your forearm or leading with your elbow is an illegal blocking zone",
   steps:["Red blocker throws a hit but extends their arm outward — forearm makes contact.",
          "From elbow to fingertips is an illegal blocking zone when the arm is extended.",
          "Forceful contact with an extended forearm or elbow warrants a penalty.",
          "Legal blocks use the torso, shoulder, and upper arm only."],
   durations:[2800,3000,2800,2600],
   why:"Extended arms add dangerous force. Keeping arms tucked is both a rules requirement and a balance technique.",
   anim:"penalty",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"cutting",title:"Cutting the Track",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"Returning from out of bounds in front of skaters you were behind is illegal",
   steps:["Teal jammer is knocked out of bounds while trying to pass red blockers.",
          "The jammer must re-enter behind any upright in-bounds skater they were behind when they left.",
          "Teal jammer re-enters in front of two red blockers — that's cutting the track.",
          "Ref signals cut. Gaining position by using the out-of-bounds area is always penalized."],
   durations:[2800,3000,2800,2600],
   why:"You can't use the out-of-bounds area as a shortcut. Re-enter behind the skaters you left behind.",
   anim:"penalty",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"oob-block",title:"Blocking Out of Bounds",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"You cannot initiate a block while fully out of bounds",
   steps:["Red blocker is pushed to the edge and steps briefly out of bounds.",
          "While out of bounds, the red blocker shoves a teal skater — illegal initiation.",
          "Skaters who are fully out of bounds may not initiate blocks, only absorb them.",
          "Ref calls the penalty. The blocker must skate to the box immediately."],
   durations:[2800,2800,2800,2600],
   why:"Out-of-bounds skaters are off the field. They can't use that position to interfere with in-bounds play.",
   anim:"penalty",refSignal:"oob",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"multi-block",title:"Multi-Player Block",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"Linking arms or forming an impenetrable chain with a teammate is illegal",
   steps:["Two red blockers lock arms to form a solid connected barrier across the track.",
          "Teal jammer attempts to push through between them — the link holds completely.",
          "Skaters may not form an impenetrable connection by grasping or linking with a teammate.",
          "The penalty is called when the opponent attempts to get through and cannot."],
   durations:[2800,3000,2800,2800],
   why:"Walls are legal — but linked, grasping connections are not.",
   anim:"wall",refSignal:"penalty",focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"foul-out",title:"Fouling Out",cat:"Penalties",catColor:"var(--cat-penalty)",
   teaser:"Seven penalties in one game and you're expelled for the rest of the bout",
   steps:["Each penalty sends a skater to the box for 30 seconds. Penalties accumulate all game.",
          "At six penalties, the skater is on the edge — one more and they're out.",
          "A seventh penalty means the skater has fouled out and must leave entirely.",
          "The team continues without that skater for the rest of the game."],
   durations:[2800,2800,2800,2800],
   why:"Penalty management is a major strategic factor. Coaches track every skater's count throughout the bout.",
   anim:"penalty",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"power-jam",title:"Power Jam",cat:"Power Jams",catColor:"var(--cat-power)",
   teaser:"One jammer sits in the penalty box — the other scores freely",
   steps:["Red jammer commits a penalty and heads to the box. Teal is the only jammer on track.",
          "Teal jammer enters the pack with zero jammer opposition.",
          "Teal laps the entire red team repeatedly, scoring four or more points per pass.",
          "Red jammer exits the box after 30 seconds. The power jam is over."],
   durations:[2800,3000,3000,2600],
   why:"A power jam can swing 20+ unanswered points in 30 seconds — the biggest momentum shift in derby.",
   anim:"power",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[4,10],jB:[18,61]},

  {id:"double-power-jam",title:"Double Power Jam",cat:"Power Jams",catColor:"var(--cat-power)",
   teaser:"Both jammers in the box at once — neither team can score",
   steps:["Red jammer commits a penalty and goes to the box.",
          "Moments later, teal jammer also commits a penalty — both are in the box simultaneously.",
          "With no jammers on track, neither team can score. Blockers just skate.",
          "The first jammer released from the box immediately triggers a power jam for their team."],
   durations:[2800,2800,2800,2800],
   why:"A double power jam neutralizes the advantage — but the first jammer out triggers a power jam.",
   anim:"pack",refSignal:"penalty",focus:"both",
   bA:[[35,21],[46,18],[57,19],[67,22]],bB:[[26,73],[19,65],[16,55],[16,45]],jA:[4,10],jB:[4,90]},

  {id:"blocker-box",title:"Blocker in the Box",cat:"Power Jams",catColor:"var(--cat-power)",
   teaser:"When a blocker is penalized, the opposing jammer has a numbers advantage",
   steps:["Red blocker takes a penalty and goes to the box — red is down to three blockers.",
          "Teal jammer now faces a thinner pack with fewer bodies to pass.",
          "The gap created by the missing blocker makes the jammer's path much easier.",
          "Blocker penalties don't trigger a power jam, but they shift scoring odds significantly."],
   durations:[2800,2800,2800,2800],
   why:"Every body on the track matters. Blocker penalties shift scoring potential significantly.",
   anim:"penalty",refSignal:"penalty",focus:"b",
   bA:[[41,19],[50,18],[59,19],[67,22]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"engagement-zone",title:"Engagement Zone",cat:"Pack Rules",catColor:"var(--cat-pack)",
   teaser:"Blocking is only legal within 20 feet of the pack in either direction",
   steps:["The pack is the largest group of in-bounds upright blockers containing members of both teams.",
          "The engagement zone extends 20 feet ahead of the foremost pack skater and 20 feet behind the rearmost.",
          "A jammer or blocker outside this zone is out of play and cannot legally block or be blocked.",
          "Blockers who go out of play are warned and must immediately return — or face a penalty."],
   durations:[2800,3000,2800,2800],
   why:"This rule keeps the action contained and prevents one team camping at the finish line.",
   anim:"engagement",refSignal:"oob",focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"pack-definition",title:"Destroying the Pack",cat:"Pack Rules",catColor:"var(--cat-pack)",
   teaser:"If one team sprints away, the pack is gone — and blocking stops",
   steps:["The pack must include upright in-bounds blockers from both teams within 10 feet of each other.",
          "Red blockers deliberately sprint forward, separating from teal by more than 10 feet.",
          "There is no longer a valid pack. Refs call 'no pack!' — all blocking must cease.",
          "All blockers from both teams must work to reform the pack or face a penalty."],
   durations:[2800,3000,2800,2800],
   why:"Pack destruction creates chaos — but intentionally destroying it is illegal and penalized.",
   anim:"pack",refSignal:"nopack",focus:"both",
   bA:[[35,21],[46,18],[57,19],[67,22]],bB:[[26,73],[19,65],[16,55],[16,45]],jA:[76,29],jB:[18,61]},

  {id:"pivot-role",title:"The Pivot",cat:"Pack Rules",catColor:"var(--cat-pack)",
   teaser:"The pivot wears a striped helmet cover and has special abilities other blockers don't",
   steps:["The pivot is a blocker who wears a helmet cover with a stripe — the only one on their team.",
          "The pivot may touch the pivot line at jam start, setting the front of the pack.",
          "Uniquely, the pivot can receive the star from their jammer and become the new jammer.",
          "The pivot is the most versatile skater on the track."],
   durations:[2800,2800,3000,2800],
   why:"The pivot bridges the roles of blocker and potential jammer.",
   anim:"lead",refSignal:null,focus:"b",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[76,29],jB:[18,61]},

  {id:"jam-start",title:"How a Jam Starts",cat:"Pack Rules",catColor:"var(--cat-pack)",
   teaser:"One whistle blast starts the blockers; a second burst starts the jammers",
   steps:["Blockers line up between the pivot line and jammer line. Pivots may touch the pivot line.",
          "One long whistle blast — blockers start skating. The pack is now in motion.",
          "A second series of whistle blasts — jammers launch from behind the jammer line.",
          "Jammers must work through a moving pack on their first pass before they can score."],
   durations:[2800,2800,2800,2800],
   why:"The staggered start gives blockers time to form up before the jammers arrive.",
   anim:"lead",refSignal:"lead",focus:"both",
   bA:[[38,20],[47,18],[56,18],[65,21]],bB:[[24,71],[19,64],[16,56],[16,47]],jA:[74,27],jB:[81,36]},
];

const CATS = ["All","Jamming","Blocking","Penalties","Power Jams","Pack Rules"];
const CAT_LABELS = {"Jamming":"Scoring","Blocking":"Blocking","Penalties":"Penalties","Power Jams":"Power Jams","Pack Rules":"Pack Rules"};
